language: go

go:
- 1.6.2

sudo: false

before_install:
  # Redo the travis setup but with the ninjasftw/libertyproxybeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/ninjasftw/libertyproxybeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/ninjasftw/libertyproxybeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/ninjasftw/libertyproxybeat
  - cd $HOME/gopath/src/github.com/ninjasftw/libertyproxybeat

install:
  - make
